target-version = "py312"
line-length = 120
extend-exclude = ["migrations"]

[lint]
select = ["B", "E4", "E7", "E9", "F", "I", "S", "UP"]

[lint.per-file-ignores]
"run.py" = ["S104"]
"tests/**/*.py" = ["S101", "S105", "S106"]
