export const roles = ['Admin', 'Citizen', 'Hospital', 'Shelter', 'Ambulance', 'NGO', 'Volunteer', 'Police', 'Fire Service'];

export const initialDisasters = [
  {
    id: 1,
    title: 'Flooding near Velachery lake bund',
    disaster_type: 'flood',
    address: 'Velachery, Chennai',
    latitude: 12.9798,
    longitude: 80.2209,
    people_affected: 320,
    severity_hint: 'high',
    status: 'active',
    score: 91,
    label: 'Critical',
    created_at: 'Today 08:20',
  },
  {
    id: 2,
    title: 'Cyclone wind damage at Cuddalore coast',
    disaster_type: 'cyclone',
    address: 'Devanampattinam, Cuddalore',
    latitude: 11.7447,
    longitude: 79.7714,
    people_affected: 180,
    severity_hint: 'high',
    status: 'active',
    score: 82,
    label: 'High',
    created_at: 'Today 09:05',
  },
  {
    id: 3,
    title: 'Landslide risk on Nilgiris ghat road',
    disaster_type: 'landslide',
    address: 'Coonoor Ghat Road, Nilgiris',
    latitude: 11.353,
    longitude: 76.7959,
    people_affected: 46,
    severity_hint: 'medium',
    status: 'monitoring',
    score: 61,
    label: 'Medium',
    created_at: 'Today 10:10',
  },
];

export const initialRescues = [
  {
    id: 101,
    disaster_id: 1,
    victim_name: 'Meena Kumar',
    victim_age: 8,
    people_count: 3,
    condition: 'critical',
    trapped: true,
    vulnerable_people: 1,
    latitude: 12.9806,
    longitude: 80.2194,
    priority_score: 97,
    priority_label: 'Critical',
    status: 'assigned',
    assigned_unit: 'TNDRF Boat Unit 2',
    notes: 'Child and two adults stranded on first-floor terrace near the canal.',
    created_at: '12 min ago',
  },
  {
    id: 102,
    disaster_id: 2,
    victim_name: 'R. Murugan',
    victim_age: 72,
    people_count: 1,
    condition: 'injured',
    trapped: false,
    vulnerable_people: 1,
    latitude: 11.7461,
    longitude: 79.7728,
    priority_score: 72,
    priority_label: 'High',
    status: 'pending',
    assigned_unit: '',
    notes: 'Tree fall injury; needs 108 ambulance and stretcher support.',
    created_at: '19 min ago',
  },
  {
    id: 103,
    disaster_id: 1,
    victim_name: 'Fathima Banu',
    victim_age: 31,
    people_count: 5,
    condition: 'stable',
    trapped: false,
    vulnerable_people: 0,
    latitude: 12.9769,
    longitude: 80.224,
    priority_score: 43,
    priority_label: 'Medium',
    status: 'en route',
    assigned_unit: 'Greater Chennai Volunteer Team A',
    notes: 'Family needs relocation to the Velachery relief camp.',
    created_at: '35 min ago',
  },
];

export const initialFacilities = {
  hospitals: [
    { id: 1, name: 'Rajiv Gandhi Govt General Hospital', available_beds: 52, total_beds: 220, icu_beds: 10, emergency_capacity: 36, status: 'ready' },
    { id: 2, name: 'Stanley Medical College Hospital', available_beds: 31, total_beds: 260, icu_beds: 6, emergency_capacity: 24, status: 'busy' },
    { id: 3, name: 'Cuddalore Govt Medical College Hospital', available_beds: 28, total_beds: 180, icu_beds: 4, emergency_capacity: 18, status: 'ready' },
  ],
  shelters: [
    { id: 1, name: 'Velachery Govt School Relief Camp', available_capacity: 420, total_capacity: 700, food_available: true, medical_support: true },
    { id: 2, name: 'Cuddalore Cyclone Shelter', available_capacity: 190, total_capacity: 360, food_available: true, medical_support: true },
    { id: 3, name: 'Coonoor Community Hall Camp', available_capacity: 74, total_capacity: 160, food_available: true, medical_support: false },
  ],
  ambulances: [
    { id: 1, vehicle_number: 'TN-01-ER-108', driver_name: 'Karthik Raj', status: 'available' },
    { id: 2, vehicle_number: 'TN-31-ER-214', driver_name: 'Ameena Begum', status: 'dispatched' },
    { id: 3, vehicle_number: 'TN-38-ER-443', driver_name: 'Prakash Selvam', status: 'available' },
  ],
};

export const initialResponseHub = {
  emergency_hotline: '112',
  news_updates: [
    {
      id: 1,
      disaster_id: 1,
      headline: 'Live: rescue boats enter isolated flood streets',
      summary: 'Verified field teams are moving food, water, and residents through the Velachery flood corridor.',
      source_name: 'ResQ verified field desk',
      state: 'Tamil Nadu',
      district: 'Chennai',
      is_live: true,
      stream_url: 'https://www.youtube.com/@DDNews/live',
    },
  ],
  welfare_checks: [],
  hospital_notifications: [],
  supply_requests: [],
  campaigns: [
    {
      id: 1,
      title: 'National Emergency Rescue & Victim Relief Fund',
      description: 'Support verified rescue transport, food, medical supplies, and recovery assistance.',
      goal_amount: 2500000,
      confirmed_amount: 0,
      pledged_amount: 0,
      currency: 'INR',
    },
  ],
  dispatches: [],
};
