export const roles = ['Admin', 'Citizen', 'Hospital', 'Shelter', 'Ambulance', 'NGO', 'Volunteer', 'Police', 'Fire Service'];

export const initialDisasters = [
  {
    id: 1,
    title: 'Flooding near Riverside Colony',
    disaster_type: 'flood',
    address: 'Riverside Colony, Kochi',
    latitude: 9.9312,
    longitude: 76.2673,
    people_affected: 240,
    severity_hint: 'high',
    status: 'active',
    score: 89,
    label: 'Critical',
    created_at: 'Today 08:20',
  },
  {
    id: 2,
    title: 'Apartment fire at Market Road',
    disaster_type: 'fire',
    address: 'Market Road, Ernakulam',
    latitude: 9.9821,
    longitude: 76.2999,
    people_affected: 65,
    severity_hint: 'high',
    status: 'active',
    score: 78,
    label: 'High',
    created_at: 'Today 09:05',
  },
  {
    id: 3,
    title: 'Landslide risk near Hill View',
    disaster_type: 'landslide',
    address: 'Hill View Road, Idukki',
    latitude: 9.8496,
    longitude: 76.9688,
    people_affected: 40,
    severity_hint: 'medium',
    status: 'monitoring',
    score: 58,
    label: 'Medium',
    created_at: 'Today 10:10',
  },
];

export const initialRescues = [
  {
    id: 101,
    disaster_id: 1,
    victim_name: 'Maya Joseph',
    victim_age: 8,
    people_count: 3,
    condition: 'critical',
    trapped: true,
    vulnerable_people: 1,
    latitude: 9.932,
    longitude: 76.269,
    priority_score: 97,
    priority_label: 'Critical',
    status: 'assigned',
    assigned_unit: 'Boat Rescue Unit 2',
    notes: 'Child and two adults on rooftop.',
    created_at: '12 min ago',
  },
  {
    id: 102,
    disaster_id: 2,
    victim_name: 'Suresh Menon',
    victim_age: 72,
    people_count: 1,
    condition: 'injured',
    trapped: false,
    vulnerable_people: 1,
    latitude: 9.981,
    longitude: 76.301,
    priority_score: 72,
    priority_label: 'High',
    status: 'pending',
    assigned_unit: '',
    notes: 'Smoke inhalation; needs ambulance.',
    created_at: '19 min ago',
  },
  {
    id: 103,
    disaster_id: 1,
    victim_name: 'Rafiq Ali',
    victim_age: 31,
    people_count: 5,
    condition: 'stable',
    trapped: false,
    vulnerable_people: 0,
    latitude: 9.929,
    longitude: 76.265,
    priority_score: 43,
    priority_label: 'Medium',
    status: 'en route',
    assigned_unit: 'Volunteer Team A',
    notes: 'Needs relocation to shelter.',
    created_at: '35 min ago',
  },
];

export const initialFacilities = {
  hospitals: [
    { id: 1, name: 'City Emergency Hospital', available_beds: 42, total_beds: 180, icu_beds: 8, emergency_capacity: 30, status: 'ready' },
    { id: 2, name: 'General Hospital Ernakulam', available_beds: 24, total_beds: 220, icu_beds: 3, emergency_capacity: 20, status: 'busy' },
  ],
  shelters: [
    { id: 1, name: 'Govt HSS Relief Camp', available_capacity: 310, total_capacity: 600, food_available: true, medical_support: true },
    { id: 2, name: 'Community Hall Camp', available_capacity: 86, total_capacity: 220, food_available: true, medical_support: false },
  ],
  ambulances: [
    { id: 1, vehicle_number: 'KL-07-ER-108', driver_name: 'Nikhil Das', status: 'available' },
    { id: 2, vehicle_number: 'KL-07-ER-214', driver_name: 'Ameena P', status: 'dispatched' },
    { id: 3, vehicle_number: 'KL-05-ER-443', driver_name: 'John Varghese', status: 'available' },
  ],
};
