"""Initial beta schema baseline

Revision ID: 20260721_01
Revises: 
Create Date: 2026-07-21 21:38:19.328433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260721_01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=60), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_assessments_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_assessments_entity_type'), ['entity_type'], unique=False)

    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('icu_beds', sa.Integer(), nullable=False),
    sa.Column('emergency_capacity', sa.Integer(), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('storage_location', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_category'), ['category'], unique=False)

    op.create_table('responder_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('skills', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('availability_status', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('responder_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responder_units_availability_status'), ['availability_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_responder_units_unit_type'), ['unit_type'], unique=False)

    op.create_table('shelters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('available_capacity', sa.Integer(), nullable=False),
    sa.Column('food_available', sa.Boolean(), nullable=False),
    sa.Column('medical_support', sa.Boolean(), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=40), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_number')
    )
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambulances_status'), ['status'], unique=False)

    op.create_table('disasters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('disaster_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('people_affected', sa.Integer(), nullable=False),
    sa.Column('severity_hint', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disasters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disasters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disasters_disaster_type'), ['disaster_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_disasters_status'), ['status'], unique=False)

    op.create_table('emergency_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=80), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('audience', sa.String(length=180), nullable=False),
    sa.Column('channels', sa.String(length=180), nullable=False),
    sa.Column('urgency', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('certainty', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_alerts_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_alerts_identifier'), ['identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_emergency_alerts_status'), ['status'], unique=False)

    op.create_table('hospital_capacity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('icu_beds', sa.Integer(), nullable=False),
    sa.Column('emergency_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_capacity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_capacity_logs_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_role'), ['role'], unique=False)

    op.create_table('role_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelter_capacity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('available_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shelter_capacity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelter_capacity_logs_shelter_id'), ['shelter_id'], unique=False)

    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.String(length=255), nullable=False),
    sa.Column('availability_status', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteers_availability_status'), ['availability_status'], unique=False)

    op.create_table('alert_acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['emergency_alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'user_id', name='uq_alert_user_ack')
    )
    with op.batch_alter_table('alert_acknowledgements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_acknowledgements_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_acknowledgements_user_id'), ['user_id'], unique=False)

    op.create_table('disaster_news_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disaster_news_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disaster_news_updates_disaster_id'), ['disaster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_news_updates_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_news_updates_is_live'), ['is_live'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_news_updates_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_news_updates_state'), ['state'], unique=False)

    op.create_table('donation_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('organizer', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_campaigns_disaster_id'), ['disaster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_campaigns_status'), ['status'], unique=False)

    op.create_table('rescue_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('victim_name', sa.String(length=120), nullable=False),
    sa.Column('victim_age', sa.Integer(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=80), nullable=False),
    sa.Column('trapped', sa.Boolean(), nullable=False),
    sa.Column('vulnerable_people', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('priority_label', sa.String(length=30), nullable=False),
    sa.Column('assigned_unit', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rescue_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rescue_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_requests_disaster_id'), ['disaster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_requests_priority_score'), ['priority_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_requests_status'), ['status'], unique=False)

    op.create_table('resource_distribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=30), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_accuracy', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_unit', sa.String(length=160), nullable=True),
    sa.Column('responder_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supply_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_requests_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_requests_disaster_id'), ['disaster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_requests_urgency'), ['urgency'], unique=False)

    op.create_table('volunteer_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('welfare_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=True),
    sa.Column('relative_name', sa.String(length=120), nullable=False),
    sa.Column('relative_phone', sa.String(length=30), nullable=True),
    sa.Column('relationship', sa.String(length=80), nullable=False),
    sa.Column('last_known_location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('requester_phone', sa.String(length=30), nullable=False),
    sa.Column('consent_to_contact', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('responder_id', sa.Integer(), nullable=True),
    sa.Column('responder_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('welfare_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_welfare_checks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_welfare_checks_disaster_id'), ['disaster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_welfare_checks_relative_name'), ['relative_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_welfare_checks_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_welfare_checks_status'), ['status'], unique=False)

    op.create_table('ambulance_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('rescue_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ),
    sa.ForeignKeyConstraint(['rescue_request_id'], ['rescue_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('donor_name', sa.String(length=120), nullable=False),
    sa.Column('donor_email', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['donation_campaigns.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_donations_status'), ['status'], unique=False)

    op.create_table('hospital_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('rescue_request_id', sa.Integer(), nullable=False),
    sa.Column('expected_patients', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['rescue_request_id'], ['rescue_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_notifications_disaster_id'), ['disaster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_notifications_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_notifications_rescue_request_id'), ['rescue_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_notifications_status'), ['status'], unique=False)

    op.create_table('location_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rescue_request_id', sa.Integer(), nullable=True),
    sa.Column('supply_request_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('consent_granted', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rescue_request_id'], ['rescue_requests.id'], ),
    sa.ForeignKeyConstraint(['supply_request_id'], ['supply_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_pings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_pings_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_pings_rescue_request_id'), ['rescue_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_pings_supply_request_id'), ['supply_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_pings_user_id'), ['user_id'], unique=False)

    op.create_table('rescue_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rescue_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rescue_request_id'], ['rescue_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rescue_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rescue_status_history_rescue_request_id'), ['rescue_request_id'], unique=False)

    op.create_table('response_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rescue_request_id', sa.Integer(), nullable=False),
    sa.Column('responder_type', sa.String(length=40), nullable=False),
    sa.Column('responder_id', sa.Integer(), nullable=False),
    sa.Column('responder_name', sa.String(length=160), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rescue_request_id'], ['rescue_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_dispatches_rescue_request_id'), ['rescue_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_dispatches_responder_type'), ['responder_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_dispatches_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_dispatches_status'))
        batch_op.drop_index(batch_op.f('ix_response_dispatches_responder_type'))
        batch_op.drop_index(batch_op.f('ix_response_dispatches_rescue_request_id'))

    op.drop_table('response_dispatches')
    with op.batch_alter_table('rescue_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rescue_status_history_rescue_request_id'))

    op.drop_table('rescue_status_history')
    with op.batch_alter_table('location_pings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_pings_user_id'))
        batch_op.drop_index(batch_op.f('ix_location_pings_supply_request_id'))
        batch_op.drop_index(batch_op.f('ix_location_pings_rescue_request_id'))
        batch_op.drop_index(batch_op.f('ix_location_pings_recorded_at'))

    op.drop_table('location_pings')
    with op.batch_alter_table('hospital_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_hospital_notifications_rescue_request_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_notifications_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_notifications_disaster_id'))
        batch_op.drop_index(batch_op.f('ix_hospital_notifications_created_at'))

    op.drop_table('hospital_notifications')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_status'))
        batch_op.drop_index(batch_op.f('ix_donations_reference'))
        batch_op.drop_index(batch_op.f('ix_donations_created_at'))
        batch_op.drop_index(batch_op.f('ix_donations_campaign_id'))

    op.drop_table('donations')
    op.drop_table('ambulance_dispatches')
    with op.batch_alter_table('welfare_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_welfare_checks_status'))
        batch_op.drop_index(batch_op.f('ix_welfare_checks_requester_id'))
        batch_op.drop_index(batch_op.f('ix_welfare_checks_relative_name'))
        batch_op.drop_index(batch_op.f('ix_welfare_checks_disaster_id'))
        batch_op.drop_index(batch_op.f('ix_welfare_checks_created_at'))

    op.drop_table('welfare_checks')
    op.drop_table('volunteer_assignments')
    with op.batch_alter_table('supply_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_requests_urgency'))
        batch_op.drop_index(batch_op.f('ix_supply_requests_status'))
        batch_op.drop_index(batch_op.f('ix_supply_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_supply_requests_disaster_id'))
        batch_op.drop_index(batch_op.f('ix_supply_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_supply_requests_category'))

    op.drop_table('supply_requests')
    op.drop_table('resource_distribution')
    with op.batch_alter_table('rescue_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rescue_requests_status'))
        batch_op.drop_index(batch_op.f('ix_rescue_requests_priority_score'))
        batch_op.drop_index(batch_op.f('ix_rescue_requests_disaster_id'))
        batch_op.drop_index(batch_op.f('ix_rescue_requests_created_at'))

    op.drop_table('rescue_requests')
    with op.batch_alter_table('donation_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_donation_campaigns_disaster_id'))

    op.drop_table('donation_campaigns')
    with op.batch_alter_table('disaster_news_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disaster_news_updates_state'))
        batch_op.drop_index(batch_op.f('ix_disaster_news_updates_published_at'))
        batch_op.drop_index(batch_op.f('ix_disaster_news_updates_is_live'))
        batch_op.drop_index(batch_op.f('ix_disaster_news_updates_district'))
        batch_op.drop_index(batch_op.f('ix_disaster_news_updates_disaster_id'))

    op.drop_table('disaster_news_updates')
    with op.batch_alter_table('alert_acknowledgements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_acknowledgements_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_acknowledgements_alert_id'))

    op.drop_table('alert_acknowledgements')
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteers_availability_status'))

    op.drop_table('volunteers')
    with op.batch_alter_table('shelter_capacity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelter_capacity_logs_shelter_id'))

    op.drop_table('shelter_capacity_logs')
    op.drop_table('role_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_role'))

    op.drop_table('notifications')
    with op.batch_alter_table('hospital_capacity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_capacity_logs_hospital_id'))

    op.drop_table('hospital_capacity_logs')
    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_emergency_alerts_identifier'))
        batch_op.drop_index(batch_op.f('ix_emergency_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_emergency_alerts_audience'))

    op.drop_table('emergency_alerts')
    with op.batch_alter_table('disasters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disasters_status'))
        batch_op.drop_index(batch_op.f('ix_disasters_disaster_type'))
        batch_op.drop_index(batch_op.f('ix_disasters_created_at'))

    op.drop_table('disasters')
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambulances_status'))

    op.drop_table('ambulances')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('shelters')
    with op.batch_alter_table('responder_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responder_units_unit_type'))
        batch_op.drop_index(batch_op.f('ix_responder_units_availability_status'))

    op.drop_table('responder_units')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_category'))

    op.drop_table('resources')
    op.drop_table('hospitals')
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_assessments_entity_type'))
        batch_op.drop_index(batch_op.f('ix_ai_assessments_entity_id'))

    op.drop_table('ai_assessments')
    # ### end Alembic commands ###
